spring:
  application:
    name: coments
  config:
    import: optional:configserver:http://localhost:8888
#spring:
#  application:
#    name: students
#  config:
#    import: optional:configserver:http://localhost:8888
#debug: true